apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus-fiber-boilerplate:9090
    isDefault: true
    editable: true

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo-fiber-boilerplate:3200
    isDefault: false
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "1ms"
        spanEndTimeShift: "-1ms"
        filterByTraceID: true
        filterBySpanID: true
        tags: ["job", "host", "pod", "namespace"]
      serviceMap:
        datasourceUid: prometheus

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki-fiber-boilerplate:3100
    isDefault: false
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"